### ISSUE TITLE
挺好玩的，重力感应不知道为什么没有触发，开启是能开启的， 但是摇动手机不行呢！？

### ISSUE THREAD

**Issue by zhangxiuyu** [BYRIO/DaBeiYou#1]

**Comment by xytoki** [comment]
安卓端在新版Chrome、微信/QQ内置浏览器测试，苹果请在Safari或微信/QQ内置浏览器测试。测试页面需要为`SecureContext`，即HTTPS页面或者localhost。如果还是无法触发，请提供手机的相关信息。

**Comment by zhangxiuyu** [comment]
修改为https可以了， 非常感谢。
