### ISSUE TITLE
请教图片替换问题

### ISSUE THREAD

**Issue by hewenzi** [BYRIO/DaBeiYou#2]
大佬您好，小白想向您请教图片预加载的问题，自己webpack 总是报错，另外assetLoader.push(url)这个方法插件不支持，没有导出assetLoader这个方法，不知道要怎么把图片加到预加载列表里😭，大佬如果看到，麻烦回复一下我，万分感谢❤

**Comment by xytoki** [comment]
如果不需要动态替换图片的话 直接替换文件夹里的文件应该就可以了
webpack报错是报错什么呢 看看能不能给个详细的日志

**Comment by hewenzi** [comment]
谢谢大佬回复，我来了，今天下午一直没连上github,才看到，sorry。
webpack 开始报错是这样的
```
D:\files\DaBeiYou>webpack
Hash: d5f3f00e62386689213e
Version: webpack 4.46.0
Time: 57ms
Built at: 2021-03-08 4:12:32 PM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for ea
ch environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in Entry module not found: Error: Can't resolve './src' in 'D:\files\DaBeiYou'
```
然后我自己加了个webpack.config.js
```
var path = require('path')

module.exports = {
    entry: path.join(__dirname, './src/main.js'), // 入口
    output: {
        // 指定输出选项
        path: path.join(__dirname, './dist'), // 输出路径
        filename: 'bundle.js', // 指定输出文件的名称
    },
    module: {
        rules: [
            { test: /\.css$/, use: ['style-loader', 'css-loader'] }, //处理css文件的规则
            { test: /\.vue$/, use: 'vue-loader' },
            { test: /\.js$/, use: 'babel-loader', exclude: /node_modules/ },
        ],
    },
    resolve: {
        alias: {
            vue$: 'vue/dist/vue.esm.js',
        },
    },
}
```
webpack 报错就这样了，就是各种说识别不了vue文件，虽然我装了vue-loader:
ERROR in ./src/main.js 
Module not found: Error: Can't resolve 'vue' in 'D:\files\DaBeiYou\src'

然后我刚刚发现，好像是因为我替换的图片问题😨，如果我从网上下载图再自己扣了换进去不会报错，如果是用大西瓜游戏提供的无底色素材就会报错，说拿不到图片的宽。谢谢大佬，可以靠抠图解决，打扰你了😝
 Uncaught (in promise) TypeError: Cannot read property 'width' of null at eval (config.js?db49:22)

**Comment by xytoki** [comment]
这个项目是用`vue-cli`构建的，只需要npm/yarn安装依赖之后直接`yarn build`或者`npm run build`就可以构建，不需要自己引入webpack和写webpack配置文件。
```
Can't resolve 'vue'
```
不是不识别vue文件，而是找不到vue库，可能是你没有装依赖...

**Comment by hewenzi** [comment]
昂，这样啊，他提示装啥依赖我就装啥了，老脸一红🐷。我一开始是用的npm run build，没有报错，只是那个图片还是识别不了，说拿不到width。后来我就以为得单独webpack才能把图片打包。应该就是图的问题，我自己p的图放进去就没事了，之前一直在用那个demo图试，留下了菜鸡的眼泪。谢谢大佬❤
